# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.cenn.ipynb.

# %% auto 0
__all__ = ['CeNN']

# %% ../../nbs/models.cenn.ipynb 3
from typing import Optional
import torch.nn as nn

from ..losses.pytorch import MAE
from ..common._base_model import BaseModel

from ..cenn.model import CeNNModel1D  # vendored, self-contained

# %% ../../nbs/models.cenn.ipynb 4
class CeNN(BaseModel):
    """CeNN

    Cellular Neural Network (CeNN) wrapper compatible with NeuralForecast's BaseModel.

    Parameters:
    - h: int, forecast horizon.
    - input_size: int, input window length.
    - n_series: int, number of time-series (multivariate).
    - hidden_dim: int=64, latent dimension for internal CeNN representation.
    - N: int=2, number of CeNN blocks in the stack.
    - K: int=4, number of recurrent CeNN steps per layer.
    - num_layers: int=3, number of CeNN layers per block.
    - dropout: float=0.1, dropout rate.
    - neighborhood: int=3, convolution kernel size (must be odd).
    - alpha_init: float=0.9, initial leak parameter (0,1).
    - enforce_bistability: bool=False, clamp center tap in A kernel for stability (depthwise case). Disabled by default for regression tasks.
    - cross_channel: bool=False, allow full cross-feature CeNN coupling across series.
    - channel_groups: int=1, number of channels per group for grouped cross-channel mixing. 1=depthwise (default), >1=grouped conv.
    - adaptive_tau: bool=False, use input-adaptive integration gate (C1).
    - dilation_schedule: str='none', dilation schedule for multi-scale templates (C2). Options: 'none', 'exponential'.
    - var_mix: bool=False, legacy alias for cross_var='varmix' (dense V x V mixing before embedding). Prefer cross_var.
    - cross_var: str='none', input cross-variable mixer {none, varmix, star}. 'varmix'=dense O(V^2) V x V matrix; 'star'=O(V)-compute STAR aggregate-redistribute core (after SOFTS), V-independent params. Takes precedence over var_mix=True when set; only active when n_series > 1.
    - pointwise_mix: bool=False, enable pointwise Conv1d(C, C, 1) channel mixing after each CeNN layer's K-loop. Adds latent cross-channel interaction (MobileNet pattern).
    - patch_len: int=None, patch length for input patching. None=no patching (default).
    - stride: int=None, stride between patches. None=non-overlapping (patch_len).
    - head_type: str='linear', prediction head type. 'linear' or 'mlp'.
    - loss: PyTorch loss, defaults to MAE().
    - valid_loss: PyTorch loss used for validation, defaults to loss.
    - plus all standard BaseModel trainer and data args.
    """

    EXOGENOUS_FUTR = False
    EXOGENOUS_HIST = False
    EXOGENOUS_STAT = False
    MULTIVARIATE = True
    RECURRENT = False

    def __init__(
        self,
        h: int,
        input_size: int,
        n_series: int,
        stat_exog_list=None,
        hist_exog_list=None,
        futr_exog_list=None,
        exclude_insample_y: bool = False,
        # CeNN-specific
        hidden_dim: int = 64,
        N: int = 2,
        K: int = 10,
        num_layers: int = 3,
        dropout: float = 0.1,
        neighborhood: int = 3,
        alpha_init: float = 0.9,
        enforce_bistability: bool = False,
        cross_channel: bool = False,
        channel_groups: int = 1,
        adaptive_tau: bool = False,
        dilation_schedule: str = "none",
        multiscale_mode: str = "none",
        integrator: str = "euler",
        var_mix: bool = False,
        cross_var: str = "none",
        pointwise_mix: bool = False,
        patch_len: Optional[int] = None,
        stride: Optional[int] = None,
        head_type: str = "linear",
        linear_skip: bool = False,
        readout_act: str = "tanh",
        trunk_type: str = "cenn",
        # Bounded gate + spectral cap (exposed so ablations can toggle them;
        # defaults match the cell defaults => no behavior change for existing variants).
        alpha_min: float = 0.5,
        alpha_max: float = 0.99,
        spectral_cap: bool = True,
        spectral_rho: float = 0.9,
        # Training
        loss: nn.Module = MAE(),
        valid_loss: Optional[nn.Module] = None,
        max_steps: int = 1000,
        learning_rate: float = 1e-3,
        num_lr_decays: int = -1,
        early_stop_patience_steps: int = -1,
        val_check_steps: int = 100,
        batch_size: int = 32,
        valid_batch_size: Optional[int] = None,
        windows_batch_size: int = 1024,
        inference_windows_batch_size: int = 1024,
        start_padding_enabled: bool = False,
        training_data_availability_threshold: float = 0.0,
        step_size: int = 1,
        scaler_type: str = "identity",
        random_seed: int = 1,
        drop_last_loader: bool = False,
        alias: Optional[str] = None,
        optimizer=None,
        optimizer_kwargs=None,
        lr_scheduler=None,
        lr_scheduler_kwargs=None,
        dataloader_kwargs=None,
        **trainer_kwargs,
    ):
        super().__init__(
            h=h,
            input_size=input_size,
            n_series=n_series,
            stat_exog_list=stat_exog_list,
            hist_exog_list=hist_exog_list,
            futr_exog_list=futr_exog_list,
            exclude_insample_y=exclude_insample_y,
            loss=loss,
            valid_loss=valid_loss if valid_loss is not None else loss,
            max_steps=max_steps,
            learning_rate=learning_rate,
            num_lr_decays=num_lr_decays,
            early_stop_patience_steps=early_stop_patience_steps,
            val_check_steps=val_check_steps,
            batch_size=batch_size,
            valid_batch_size=valid_batch_size,
            windows_batch_size=windows_batch_size,
            inference_windows_batch_size=inference_windows_batch_size,
            start_padding_enabled=start_padding_enabled,
            training_data_availability_threshold=training_data_availability_threshold,
            step_size=step_size,
            scaler_type=scaler_type,
            random_seed=random_seed,
            drop_last_loader=drop_last_loader,
            alias=alias,
            optimizer=optimizer,
            optimizer_kwargs=optimizer_kwargs,
            lr_scheduler=lr_scheduler,
            lr_scheduler_kwargs=lr_scheduler_kwargs,
            dataloader_kwargs=dataloader_kwargs,
            **trainer_kwargs,
        )

        self.c_out = self.loss.outputsize_multiplier

        # Inner CeNN model (multivariate)
        self.model = CeNNModel1D(
            n_features=n_series,
            seq_length=self.input_size,
            pred_length=self.h,
            hidden_dim=hidden_dim,
            N=N,
            K=K,
            dropout=dropout,
            num_layers=num_layers,
            neighborhood=neighborhood,
            alpha_init=alpha_init,
            enforce_bistability=enforce_bistability,
            cross_channel=cross_channel,
            channel_groups=channel_groups,
            adaptive_tau=adaptive_tau,
            dilation_schedule=dilation_schedule,
            multiscale_mode=multiscale_mode,
            integrator=integrator,
            var_mix=var_mix,
            cross_var=cross_var,
            pointwise_mix=pointwise_mix,
            patch_len=patch_len,
            stride=stride,
            head_type=head_type,
            linear_skip=linear_skip,
            readout_act=readout_act,
            trunk_type=trunk_type,
            alpha_min=alpha_min,
            alpha_max=alpha_max,
            spectral_cap=spectral_cap,
            spectral_rho=spectral_rho,
            output_multiplier=self.c_out,
        )

    def forward(self, windows_batch):
        # Extract historic values (insample_y) with shape [B, L, n_series]
        x = windows_batch["insample_y"]  # [B, L, n_series]
        out = self.model(x)  # [B, h, n_series * c_out]
        return out
